default_agent: edicraft
agents:
  edicraft:
    name: edicraft
    entrypoint: /Users/ngl/git/edicraft/agent.py
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/ngl/git/edicraft
    aws:
      execution_role: arn:aws:iam::447783235956:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-e947ba7ac5
      execution_role_auto_create: false
      account: '447783235956'
      region: us-east-1
      ecr_repository: 447783235956.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-edicraft
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: edicraft-x3EKGlCKfC
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:447783235956:runtime/edicraft-x3EKGlCKfC
      agent_session_id: 3690229c-678f-4437-b58e-e20aac0010e9
    codebuild:
      project_name: bedrock-agentcore-edicraft-builder
      execution_role: arn:aws:iam::447783235956:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-e947ba7ac5
      source_bucket: bedrock-agentcore-codebuild-sources-447783235956-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: edicraft_mem-u3YLboHgqo
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:447783235956:memory/edicraft_mem-u3YLboHgqo
      memory_name: edicraft_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
