#!/bin/bash

echo "🧪 Testing All Renewable Energy Fixes"
echo "======================================"
echo ""

# Colors
GREEN='\033[0.32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Test queries
TERRAIN_QUERY="analyze terrain at 35.067482, -101.395466"
LAYOUT_QUERY="optimize layout for test-project"
WAKE_QUERY="run wake simulation for test-project"
WINDROSE_QUERY="show me a wind rose for 35.067482, -101.395466"
REPORT_QUERY="generate report for test-project"

echo "📋 Test Queries:"
echo "   1. Terrain: $TERRAIN_QUERY"
echo "   2. Layout: $LAYOUT_QUERY"
echo "   3. Wake: $WAKE_QUERY"
echo "   4. Wind Rose: $WINDROSE_QUERY"
echo "   5. Report: $REPORT_QUERY"
echo ""

echo "🔍 Manual Testing Required:"
echo ""
echo "For each query above:"
echo "   1. Enter query in chat interface"
echo "   2. Check browser console (F12)"
echo "   3. Verify artifact renders correctly"
echo "   4. Check for action buttons below artifact"
echo ""

echo "✅ Expected Results:"
echo ""
echo "1. TERRAIN ANALYSIS"
echo "   - TerrainMapArtifact renders"
echo "   - Interactive Leaflet map shows"
echo "   - Metrics display (suitability, exclusion zones)"
echo "   - Action button: 'Optimize Turbine Layout'"
echo ""

echo "2. LAYOUT OPTIMIZATION"
echo "   - LayoutMapArtifact renders"
echo "   - Turbine positions show ONCE (not twice) ✨ FIXED"
echo "   - Map shows turbine markers"
echo "   - Stats: turbine count, capacity, spacing"
echo "   - Action button: 'Run Wake Simulation'"
echo ""

echo "3. WAKE SIMULATION ✨ FIXED"
echo "   - SimulationChartArtifact renders"
echo "   - Performance metrics display"
echo "   - Charts/visualizations load"
echo "   - Action button: 'Generate Report'"
echo ""

echo "4. WIND ROSE ANALYSIS"
echo "   - WindRoseArtifact renders"
echo "   - Interactive Plotly chart shows (NOT PNG)"
echo "   - Dark background with colored bars"
echo "   - Hover tooltips work"
echo "   - Action button: 'Generate Report'"
echo ""

echo "5. REPORT GENERATION"
echo "   - ReportArtifact renders (NOT layout)"
echo "   - Executive summary displays"
echo "   - Recommendations show"
echo "   - Action button: 'Start New Project'"
echo ""

echo "🐛 Debug Checklist:"
echo ""
echo "If something doesn't work:"
echo ""
echo "1. Check Browser Console"
echo "   - Look for error messages"
echo "   - Check for debug logs:"
echo "     • 🌹 Orchestrator wind_rose_analysis mapping"
echo "     • 🌊 Orchestrator wake_simulation mapping"
echo "     • 📄 Orchestrator report_generation mapping"
echo "     • 🎉 EnhancedArtifactProcessor: Rendering [Component]"
echo ""

echo "2. Check Lambda Logs"
echo "   # Find function names"
echo "   aws lambda list-functions | grep -i renewable"
echo ""
echo "   # Tail orchestrator logs"
echo "   aws logs tail /aws/lambda/[orchestrator-name] --follow"
echo ""
echo "   # Tail simulation logs"
echo "   aws logs tail /aws/lambda/[simulation-name] --follow"
echo ""

echo "3. Verify Environment Variables"
echo "   aws lambda get-function-configuration \\"
echo "     --function-name [orchestrator-name] \\"
echo "     --query 'Environment.Variables'"
echo ""

echo "4. Check Artifact Data"
echo "   - Open browser DevTools"
echo "   - Go to Network tab"
echo "   - Find GraphQL request"
echo "   - Check response artifacts array"
echo "   - Verify artifact.type matches expected"
echo ""

echo "📊 Success Metrics:"
echo ""
echo "✅ All 5 queries work end-to-end"
echo "✅ Correct artifacts render for each"
echo "✅ No duplicate stats in layout"
echo "✅ Wake simulation renders (was broken)"
echo "✅ Action buttons appear below artifacts"
echo "✅ No console errors"
echo "✅ No Lambda errors in logs"
echo ""

echo "🚀 Ready to Test!"
echo ""
echo "Open your application and start testing with the queries above."
echo "Report any issues with:"
echo "   - Query used"
echo "   - What rendered (or didn't)"
echo "   - Browser console errors"
echo "   - Lambda log errors"
echo ""
