# Hadolint configuration for Dockerfile linting
# Ignores the platform flag warning since we intentionally use linux/amd64 for AWS Lambda

ignored:
  - DL3006  # Always tag the version of an image explicitly
  - DL3029  # Do not use --platform flag with FROM (we need this for AWS Lambda)

trustedRegistries:
  - docker.io
  - public.ecr.aws
